In [14]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
x = [5,9,3,7]
y=[18,21,8,19]

In [15]:
a = pd.DataFrame(x)
b = pd.DataFrame(y)

In [16]:
model = LinearRegression()
model.fit(a,b)

LinearRegression()

In [17]:
model.coef_

array([[2.]])

In [18]:
model.intercept_

array([4.5])

In [19]:
#Check the same with the formula that we have written
np.corrcoef(x,y)

array([[1.        , 0.88998832],
       [0.88998832, 1.        ]])

In [20]:
np.std(x)

2.23606797749979

In [21]:
np.std(y)

5.024937810560445

In [22]:
m = 0.88998832 * (np.std(y)/np.std(x))
print(m)

2.0000000022922335


In [24]:
#c = y_bar - m*x_bar

16.5

In [27]:
c = np.mean(y) - (m*np.mean(x))
print(round(c,2))

4.5
